
const menuElementos=[
{id:1,category:"Huevos",subcategory:null,nombre:"Omelette de jamón y queso Monterrey Jack",description:"Un par de huevos acompañados de salsa a elegir (roja o verde). Frijoles refritos y totoposte de la región.",price:90,},
{id:2,category:"Huevos",subcategory:null,nombre:"Omelette de espinacas",description:"Un par de huevos batidos, rellenos de champiñones, tomate cherry y queso Monterrey Jack. Acompañados de salsa a elegir (roja o verde), frijoles refritos y totoposte de la región.",price:90,},
{id:3,category:"Huevos",subcategory:null,nombre:"Huevos clásicos",description:"Un par de huevos revueltos con jamón de pavo. Acompañados de frijoles fritos, plátanos y totoposte de la región.",price:80,},
{id:4,category:"Huevos",subcategory:null,nombre:"Huevos Beef",description:"Un par de huevos revueltos con salchicha de res. Acompañados de frijoles fritos, plátanos y totoposte de la región.",price:85,},
{id:5,category:"Huevos",subcategory:null,nombre:"Huevos a la mexicana",description:"Un par de huevos revueltos con tomate, cebolla y chile serrano. Acompañados de frijoles fritos, plátanos y totospote de la región",price:80,},
{id:6,category:"Huevos",subcategory:null,nombre:"Huevos jabalí",description:"Un par de huevos revueltos con longaniza de la región. Acompañados de frijoles fritos, plátanos y totoposte de la región.",price:85,},
{id:7,category:"Huevos",subcategory:null,nombre:"Huevos motuleños",description:"Un par de huevos estrellados sobre una cama de tortilla, queso y jamón, bañados con salsa a elegir (verde o roja) y chícharos. Acompañados de frijoles fritos, plátano frito.",price:100,},
{id:8,category:"Chilaquiles",subcategory:null,nombre:"Rojos o verdes",description:"Tortilla frita bañada con salsa de su preferencia, crema, queso Monterrey Jack, aguacate y cebolla curtida. Proteína a elegir: huevo, pollo, sirloin o chicharrón",price:80,},
{id:9,category:"Especiales",subcategory:"Toast",nombre:"Jamón serrano",description:"Un par de rebanadas de masa madre con semillas. Montado en una cama de guacamole, queso crema, tomate cherry, hojas verdes y aderezo de la casa.",price:90,},
{id:10,category:"Especiales",subcategory:"Toast",nombre:"Salmón ahumado",description:"Un par de rebanadas de masa madre con semillas. Montado en una cama de guacamole, queso crema, tomate cherry, hojas verdes y aderezo de la casa.",price:100,},
{id:11,category:"Especiales",subcategory:"Toast",nombre:"Huevos estrellados",description:"Un par de rebanadas de masa madre con semillas. Montado en una cama de guacamole, queso crema, tomate cherry, hojas verdes y aderezo de la casa.",price:90,},
{id:12,category:"Especiales",subcategory:"Toast",nombre:"Dulces",description:"Un par de rebenadas de pan de masa madre con semillas. Montado sobre una cama de queso crema con coulis de frutas (durazno, fresa, maracuyá, piña o moras).",price:75,},
{id:13,category:"Especiales",subcategory:"Bagels",nombre:"Jamón serrano",description:"Una pieza de bagels de parmesano. Montado en una cama de guacamole, queso crema, hojas verdes y aderezo de la casa.",price:85,},
{id:14,category:"Especiales",subcategory:"Bagels",nombre:"Salmón ahumado",description:"Una pieza de bagels de parmesano. Montado en una cama de guacamole, queso crema, hojas verdes y aderezo de la casa.",price:95,},
{id:15,category:"Especiales",subcategory:"Bagels",nombre:"Huevos estrellados",description:"Una pieza de bagels de parmesano. Montado en una cama de guacamole, queso crema, hojas verdes y aderezo de la casa.",price:85,},
{id:16,category:"Especiales",subcategory:"Bagels",nombre:"Clásico",description:"Una pieza de bagels de parmesano con dos rebanadas de jamón, queso Monterrey Jack, hojas verdes y aderezo de la casa.",price:80,},
{id:17,category:"Especiales",subcategory:"Dogopizza",nombre:"Champiñón",description:"Combinación de hotdog con nuestra salsa para pizza. Cubierto de queso Monterrey Jack y aderezo de la casa.",price:75,},
{id:18,category:"Especiales",subcategory:"Dogopizza",nombre:"Hawaiano",description:"Combinación de hotdog con nuestra salsa para pizza. Cubierto de queso Monterrey Jack y aderezo de la casa.",price:75,},
{id:19,category:"Especiales",subcategory:"Dogopizza",nombre:"Pepperoni",description:"Combinación de hotdog con nuestra salsa para pizza. Cubierto de queso Monterrey Jack y aderezo de la casa.",price:75,},
{id:20,category:"Especiales",subcategory:"Ensalada",nombre:"Espresso",description:"Mezcla de espinaca baby, bolitas de queso crema, arándanos deshidratados, nueces, trozos de durazno y aderezo de miel con mostaza.",price:85,},
{id:21,category:"Bebidas calientes",subcategory:null,nombre:"Espresso",description:null,price:30,},
{id:22,category:"Bebidas calientes",subcategory:null,nombre:"Espresso doble cortado",description:null,price:40,},
{id:23,category:"Bebidas calientes",subcategory:null,nombre:"Americano",description:null,price:45,},
{id:24,category:"Bebidas calientes",subcategory:null,nombre:"Filtrado de especialidad",description:"Método de extracción: V60, Chemex o prensa francesa.",price:70,},
{id:25,category:"Bebidas calientes",subcategory:null,nombre:"Latte",description:null,price:60,},
{id:26,category:"Bebidas calientes",subcategory:null,nombre:"Latte con sabor",description:"Mocca, cajeta, crema irlandesa, vainilla, caramelo.",price:65,},
{id:27,category:"Bebidas calientes",subcategory:null,nombre:"Matcha latte",description:null,price:65,},
{id:28,category:"Bebidas calientes",subcategory:null,nombre:"Taro latte",description:null,price:65,},
{id:29,category:"Bebidas calientes",subcategory:null,nombre:"Dirty chai latte",description:null,price:70,},
{id:30,category:"Bebidas calientes",subcategory:null,nombre:"Español latte",description:null,price:65,},
{id:31,category:"Bebidas calientes",subcategory:null,nombre:"Chocolate",description:null,price:65,},
{id:32,category:"Bebidas calientes",subcategory:null,nombre:"Tizana",description:null,price:55,},
{id:33,category:"Bebidas frías",subcategory:null,nombre:"Americano frío",description:null,price:50,},
{id:34,category:"Bebidas frías",subcategory:null,nombre:"Latte frío",description:null,price:60,},
{id:35,category:"Bebidas frías",subcategory:null,nombre:"Late frío con sabor",description:"Mocca, cajeta, crema irlandesa, vainilla, caramelo.",price:65,},
{id:36,category:"Bebidas frías",subcategory:null,nombre:"Matcha latte frío",description:null,price:65,},
{id:37,category:"Bebidas frías",subcategory:null,nombre:"Matcha / fresa latte frío",description:null,price:75,},
{id:38,category:"Bebidas frías",subcategory:null,nombre:"Matcha / coco latte frío",description:null,price:80,},
{id:39,category:"Bebidas frías",subcategory:null,nombre:"Taro latte frío",description:null,price:65,},
{id:40,category:"Bebidas frías",subcategory:null,nombre:"Taro / fresa latte frío",description:null,price:75,},
{id:41,category:"Bebidas frías",subcategory:null,nombre:"Taro / coco latte frío",description:null,price:80,},
{id:42,category:"Bebidas frías",subcategory:null,nombre:"Español latte frío",description:null,price:65,},
{id:43,category:"Refresh",subcategory:null,nombre:"Fresa refresh",description:"Base a elegir: limonada, agua mineral o leche.",price:55,},
{id:44,category:"Refresh",subcategory:null,nombre:"Moras refresh",description:"Base a elegir: limonada, agua mineral o leche.",price:55,},
{id:45,category:"Refresh",subcategory:null,nombre:"Mango refresh",description:"Base a elegir: limonada, agua mineral o leche.",price:55,},
{id:46,category:"Refresh",subcategory:null,nombre:"Manzana verde refresh",description:"Base a elegir: limonada, agua mineral o leche.",price:55,},
{id:47,category:"Frozen",subcategory:null,nombre:"Fresa yogurt",description:null,price:75,},
{id:48,category:"Frozen",subcategory:null,nombre:"Maracuyá yogurt",description:null,price:75,},
{id:49,category:"Frozen",subcategory:null,nombre:"Frutos rojos yogurt",description:null,price:75,},
{id:50,category:"Frozen",subcategory:null,nombre:"Zarzamora yogurt",description:null,price:75,},
{id:51,category:"Frozen",subcategory:null,nombre:"Maracoco yogurt",description:null,price:75,},
{id:52,category:"Frozen",subcategory:null,nombre:"Taro frozen",description:null,price:85,},
{id:53,category:"Frozen",subcategory:null,nombre:"Matcha Frozen",description:null,price:85,},
{id:54,category:"Frozen",subcategory:null,nombre:"Chai vainilla frozen",description:null,price:85,},
{id:55,category:"Especiales",subcategory:null,nombre:"Carajillo",description:"Mezcla de licor especiado con espresso doble.",price:70,},
{id:56,category:"Especiales",subcategory:null,nombre:"Carajillo especial",description:"Mezcla de licor especiado con espresso doble y con un shot de Baileys.",price:80,},
{id:57,category:"Especiales",subcategory:null,nombre:"Affogato",description:"Helado doble de vainilla con un shot de espresso.",price:70,},
{id:58,category:"Especiales",subcategory:null,nombre:"Affogato especial",description:"Helado doble con un shot de espresso y un shot de Baileys",price:80,},
{id:59,category:"Especiales",subcategory:null,nombre:"Tinto de verano",description:"Vino espumo lambrusco, shot de limón, agua mineral y Gingerale",price:70,},
{id:60,category:"Especiales",subcategory:null,nombre:"Calimocho",description:"Vino espumo lambrusco, Coca-Cola y rodajas de limón",price:70,},
{id:61,category:"Pre-Workout",subcategory:null,nombre:"Monster americano",description:null,price:70,},
{id:62,category:"Pre-Workout",subcategory:null,nombre:"Cold brew latte",description:null,price:70,},
{id:63,category:"Pre-Workout",subcategory:null,nombre:"Cold brew Gingerale",description:null,price:70,},
{id:64,category:"Pre-Workout",subcategory:null,nombre:"Cold brew Sunrise",description:null,price:70,},
{id:65,category:"Extras",subcategory:null,nombre:"Shot extra café",description:null,price:15,},
{id:66,category:"Extras",subcategory:null,nombre:"Cambio de leche",description:null,price:12,},
{id:67,category:"Extras",subcategory:null,nombre:"Refresco, agua mineral",description:null,price:25,},
{id:68,category:"Extras",subcategory:null,nombre:"Jugos",description:null,price:18,},
{id:69,category:"Extras",subcategory:null,nombre:"Agua",description:null,price:16,},
{id:70,category:"Extras",subcategory:null,nombre:"Powerade",description:null,price:30,},
{id:71,category:"Extras",subcategory:null,nombre:"Amper, agua de coco",description:null,price:37,},
{id:72,category:"Extras",subcategory:null,nombre:"Palomitas",description:null,price:25,}
]